spring:

  datasource:
    url: jdbc:postgresql://database-1.caf4e3izss8r.us-east-1.rds.amazonaws.com/accountdatabasestaging
    username: accountdatabaseuser
    password: yourpassword

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
