# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven


#  De CI pipeline zal het project bouwen, unit- en integratie testen uitvoeren,
# de sonar analyse uitvoeren, de Docker image bouwen
# deze stappen succesvol zijn de versie in de GitHub repo taggen.

#sonar token: 66d58841310565a0ce131f42d78a931090915738
# mvn sonar:sonar \ -Dsonar.projectKey=BankAccountServiceCICD \ -Dsonar.host.url=http://sonar.cloud-native-minor.it -Dsonar.login=66d58841310565a0ce131f42d78a931090915738
name: BankAccountServiceCICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  sonarqube:
    runs-on: ubuntu-latest
    steps:
      run: |
        mvn -B sonar:sonar -Dsonar.projectKey=BankAccountServiceCICD \
        -Dsonar.host.url=http://sonar.cloud-native-minor.it \
        -Dsonar.host.url=http://sonar.cloud-native-minor.it \
        -Dsonar.login=66d58841310565a0ce131f42d78a931090915738 \
        -Dsonar.qualitygate.wait=true \
        -Dsonar.qualitygate.timeout=60

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B test --file pom.xml 

